action_id: trunk-single-player-auto-upgrade
date: 2025-06-26 16:14:17
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-single-player-auto-upgrade'. See .trunk\out\UVrrc.yaml for details.
  error_path: C:\Users\tyler\Documents\devel\github\projects\ai-tools\.trunk\out\UVrrc.yaml
timestamp: 1750954457
full_timestamp:
  nanos: 91392000
  seconds: 1750954457
trunk_version: 1.24.0
