action_id: trunk-cache-prune
date: 2025-06-26 15:09:13
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1750950553
full_timestamp:
  nanos: 736463000
  seconds: 1750950553
trunk_version: 1.24.0
