@echo off
REM Generated by trunk tool 'bandit'
set PATH=C:\Users\tyler\AppData\Local\trunk\tools\bandit\1.8.5-525f91c97737ff5a2395e6321797a67d/bin;C:\Users\tyler\AppData\Local\trunk\tools\bandit\1.8.5-525f91c97737ff5a2395e6321797a67d/Scripts;C:\Users\tyler\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\tyler\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set VIRTUAL_ENV=C:\Users\tyler\AppData\Local\trunk\tools\bandit\1.8.5-525f91c97737ff5a2395e6321797a67d
set PYTHONUTF8=1

start /w /b bandit %*
