@echo off
REM Generated by trunk tool 'checkov'
set PATH=C:\Users\tyler\AppData\Local\trunk\tools\checkov\3.2.447-aab680977ceed495ff6ffb114d3689d3/bin;C:\Users\tyler\AppData\Local\trunk\tools\checkov\3.2.447-aab680977ceed495ff6ffb114d3689d3/Scripts;C:\Users\tyler\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\tyler\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set VIRTUAL_ENV=C:\Users\tyler\AppData\Local\trunk\tools\checkov\3.2.447-aab680977ceed495ff6ffb114d3689d3
set PYTHONUTF8=1

start /w /b checkov %*
