@echo off
REM Generated by trunk tool 'isort'
set PATH=C:\Users\tyler\AppData\Local\trunk\tools\isort\6.0.1-82a699cda410b78cd124f9d988ca64d6/bin;C:\Users\tyler\AppData\Local\trunk\tools\isort\6.0.1-82a699cda410b78cd124f9d988ca64d6/Scripts;C:\Users\tyler\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\tyler\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\tyler\AppData\Local\trunk\tools\isort\6.0.1-82a699cda410b78cd124f9d988ca64d6

start /w /b isort %*
