@echo off
REM Generated by trunk tool 'prettier'
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\tyler\AppData\Local\trunk\tools\prettier\3.6.1-084aa727f539db6f29f3d6fb4ebb0f05/node_modules/.bin;C:\Users\tyler\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c/bin;C:\Users\tyler\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set NODE_PATH=C:\Users\tyler\AppData\Local\trunk\tools\prettier\3.6.1-084aa727f539db6f29f3d6fb4ebb0f05/node_modules

start /w /b prettier %*
