@echo off
REM Generated by trunk tool 'ruff'
set PATH=C:\Users\tyler\AppData\Local\trunk\tools\ruff\0.12.0-2b5d0b7d4fa442a3b36a99235652d53d/bin;C:\Users\tyler\AppData\Local\trunk\tools\ruff\0.12.0-2b5d0b7d4fa442a3b36a99235652d53d/Scripts;C:\Users\tyler\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\tyler\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\tyler\AppData\Local\trunk\tools\ruff\0.12.0-2b5d0b7d4fa442a3b36a99235652d53d

start /w /b ruff %*
