@echo off
REM Generated by trunk tool 'taplo'
set PATH=C:\Users\tyler\AppData\Local\trunk\tools\taplo\0.9.3-161a8e6f27aed684fba375bac898ed36;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b taplo %*
