@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\tyler\AppData\Local\trunk\tools\trufflehog\3.89.2-ab97d3228fe4893489b3ee12607c3189;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\tyler\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
